### ISSUE TITLE
Zvážit možnost použití material designu

### ISSUE THREAD

**Issue by jaroslavpsenicka** [momega/saga#1]
viz například [Google Inbox](https://inbox.google.com/?cid=imp&pli=1).

**Comment by momega** [comment]
Jsem pro. Prosel jsem si https://material.angularjs.org/latest/ a vypada to fakt hezky. Webjar je taky ready.

**Comment by jaroslavpsenicka** [comment]
Webjar jde použít, ikony jsem ale [musel referencovat](https://fonts.googleapis.com/icon?family=Material+Icons). Mohl bych se pokusit font stáhnout [jak je popsáno zde](http://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server).
