### ISSUE TITLE
Promyslet multi-tenant přístup

### ISSUE THREAD

**Issue by jaroslavpsenicka** [momega/saga#2]
Jak bude řešení navrženo ohledem více klientů

- každý bude mít vlastní instanci
- bude zavedeno něco jako "projekt" který bude možné sdílet mezi uživateli

Na dahsboardu bych pak viděl všechny tasky ze všech projektů, kam mám přístup.

**Comment by momega** [comment]
Promysleno, zakladame instanci Project s vazbou na ProcessModel a dalsi
