### ISSUE TITLE
ProcessModel vs. Model

### ISSUE THREAD

**Issue by momega** [momega/saga#7]
Proc mame org.saga.design.model.Model a org.saga.design.model.ProcessModel? Neni to zbytecne?

**Comment by jaroslavpsenicka** [comment]
myslím, že budeme potřebovat 

1. datový objekt reprezentující model procesu
1. entitu, kterou uložíme do mongodb, která může mj. obsahovat id, referenci na projekt/tenanta (pokud to budeme chtít dělat takto)

proto dvě, ale možná by to šlo sloučit

**Comment by momega** [comment]
Opravdu zavisi jaky zvolime pristup.

**Comment by momega** [comment]
Model odstranen, zustava uz jen ProcessModel
